// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW8WpbSHeW3_gyo-q6Cs-3Uc7-6lkXcJQ',
    appId: '1:1055488670149:android:25370f46a0b870a21b33ac',
    messagingSenderId: '1055488670149',
    projectId: 'fitflow-b9a2e',
    databaseURL: 'https://fitflow-b9a2e-default-rtdb.firebaseio.com',
    storageBucket: 'fitflow-b9a2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfX0LEW8fGmCjX7dtrP3hc-dMQaseDTo0',
    appId: '1:1055488670149:ios:554afb81300e18d31b33ac',
    messagingSenderId: '1055488670149',
    projectId: 'fitflow-b9a2e',
    databaseURL: 'https://fitflow-b9a2e-default-rtdb.firebaseio.com',
    storageBucket: 'fitflow-b9a2e.firebasestorage.app',
    iosBundleId: 'com.example.fitFlow',
  );
}
